version: "3.3"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - rede-nifi-kafka
    volumes:
      - "zookeeper-data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - TZ=America/Sao_Paulo
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
  kafka:
    depends_on:
      - zookeeper
    image: docker.io/bitnami/kafka:3.4
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    networks:
      - rede-nifi-kafka
    volumes:
      - "kafka-data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - TZ=America/Sao_Paulo
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
  nifi:
    depends_on:
      - kafka
    hostname: nifi
    image: apache/nifi:1.19.0
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=nifi
      - SINGLE_USER_CREDENTIALS_PASSWORD=mkYUQBJ9BBhc38RWa1p3E76xUR1rhYGR
      - TZ=America/Sao_Paulo
    deploy:
      resources:
        limits:
          memory: 4G
    restart: on-failure
    healthcheck:
      test: wget -q --spider http://nifi:8443/nifi-api/system-diagnostics
      interval: 60s
      timeout: 40s
      retries: 3
    volumes:
      - nifi-logs:/opt/nifi/nifi-current/logs
      - nifi-conf:/opt/nifi/nifi-current/conf
      - nifi-state:/opt/nifi/nifi-current/state
      - nifi-content:/opt/nifi/nifi-current/content_repository
      - nifi-database:/opt/nifi/nifi-current/database_repository
      - nifi-flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi-provenance:/opt/nifi/nifi-current/provenance_repository
    networks:
      - rede-nifi-kafka
  control-center:
    depends_on:
      - kafka
    hostname: control-center
    image: confluentinc/cp-enterprise-control-center:7.3.0
    container_name: control-center
    ports:
      - "19021:9021"
    deploy:
      resources:
        limits:
          memory: 2GB
    restart: always
    environment:
      - CONTROL_CENTER_BOOTSTRAP_SERVERS=kafka:9092
      - CONTROL_CENTER_ZOOKEEPER_CONNECT=zookeeper:2181
      - CONTROL_CENTER_REPLICATION_FACTOR=1
      - CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS=1
      - CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS=1
      - CONTROL_CENTER_COMMAND_TOPIC_PARTITIONS=1
      - CONTROL_CENTER_METRICS_TOPIC_PARTITIONS=1
      - PORT=9021
      - TZ=America/Sao_Paulo
    networks:
      - rede-nifi-kafka

volumes:
  zookeeper-data:
  kafka-data:
  nifi-logs:
  nifi-conf:
  nifi-state:
  nifi-content:
  nifi-database:
  nifi-flowfile:
  nifi-provenance:

networks:
  rede-nifi-kafka:
    driver: bridge